# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1fd1c24fb757603ec8962bf685bb7ddc079edf75e534619eacca974dde010fa46269ec1a08b535467cd02df11fd9de0d2fe9295b0c4a551687adae8e1d9ea6a

test:
  secret_key_base: b730e6f4217cae5e7503cbfb782654dcb941c60e92ed1b0fba86848420ae759d7a5e768538af61016b2c448658541599afd250d70fa8fe5c25067d946d9b228e

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
